phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t emplify-server:latest .
      - docker tag emplify-server:latest 854139699217.dkr.ecr.ap-southeast-1.amazonaws.com/emplify-server:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 854139699217.dkr.ecr.ap-southeast-1.amazonaws.com/emplify-server:latest
